Apps/Aplicacion1/urls.py
from django.conf.urls import url,include
from .views import EliminarEstudianteView,EstudianteList,IndexView,EstudianteView,crearEstudianteView,crearBusView,EditarBusView,EliminarBusView,BusList,LoginView,logout_view,EditarEstudianteView
#from django.contrib.auth import views as auth_views

urlpatterns = [
	url(r'^$', IndexView.as_view(),name='home'),
	url(r'^Estudiante$', EstudianteView.as_view(),name='Estudiante'),
	url(r'^EstudianteList$', EstudianteList,name='EstudianteList'),
	url(r'^Bus$', BusList,name='BusList'),


	
	url(r'^AddEstudiante$', crearEstudianteView.as_view(),name='addEstudiante'),
	url(r'^AddBus$', crearBusView.as_view(),name='addBus'),
	url(r'^login$', LoginView.as_view(),name='login'),
	url(r'^logout$', logout_view,name='logout'),


	#url(r'^logout/$', auth_views.logout, {'next_page': 'App1:home'}, name='logout'),


	url(r'^EliminarEstudiante/(?P<pk>\d+)/$', EliminarEstudianteView.as_view(), name='DeleteEstudiante'),
	url(r'^EliminarBus/(?P<pk>\d+)/$', EliminarBusView.as_view(), name='DeleteBus'),
	

	
	url(r'^EditarBus/(?P<pk>\d+)/', EditarBusView.as_view(), name='EditarBus'),
	url(r'^EditarEstudiante/(?P<pk>\d+)/$', EditarEstudianteView.as_view(), name='EditarEstudiante'),



	

]

Apps/usuario/urls.py
from django.conf.urls import url,include
from .views import RegistroUsuario
#from django.contrib.auth import views as auth_views

urlpatterns = [
	url(r'^Registro$', RegistroUsuario.as_view(),name='Registro'),
]

proyecto1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
  # 	url(r'^App1/', include('Apps.Aplicacion1.urls',namespace='App1')),
    url(r'^App1/', include('Apps.Aplicacion1.urls',namespace='App1')),
    url(r'^usuario/', include('Apps.usuario.urls',namespace='usuario')),


    url(r'^admin/', admin.site.urls),

]

Apps/Aplicacion1/models.py
from __future__ import unicode_literals
from django.db import models


# Create your models here.


class Bus(models.Model):
    noBus = models.CharField(max_length=30)
    creacion = models.DateTimeField(auto_now_add=True)
    modificar = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.nombre
        #return '%s %s' % (self.nombre, self.carne)

class Estudiante(models.Model):
    carne = models.CharField(max_length=30)
    nombre = models.CharField(max_length=30)
    bus = models.ForeignKey(Bus)

    creacion = models.DateTimeField(auto_now_add=True)
    modificar = models.DateTimeField(auto_now=True)


    def __str__(self):
        return  self.nombre
         #return '%s %s' % (self.nombre, self.carne)

Apps/usuario/models.py
from django.db import models

# Create your models here.

Apps/Aplicacion1/forms.py
from django import forms
from .models import Estudiante,Bus

class EstudianteForm(forms.ModelForm):
	 class Meta:
	 	model = Estudiante
	 	fields = '__all__'


	 	
class BusForm(forms.ModelForm):
	 class Meta:
	 	model = Bus
	 	fields = '__all__'

Apps/usuario/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistroForm(UserCreationForm):

	class Meta:
		model= User
		fields= [
				'username',
				'first_name',
				'last_name',
				'email',

		]
		labels = {
				'username': 'Nombre de usuario',
				'first_name': 'Nombrre',
				'last_name': 'Apellido',
				'email': 'Correo Electronico',


		}

Apps/Aplicacion1/views.py
from __future__ import unicode_literals
#from django.views.generic.edit import FormView



from django.shortcuts import render
from django.views.generic import TemplateView,CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy

from .forms import EstudianteForm,BusForm
from .models import Estudiante,Bus

from django.contrib.auth.forms import AuthenticationForm


from django.contrib.auth import login
from django.views.generic import FormView
from django.contrib.auth import logout
from django.shortcuts import redirect



def EstudianteList(request):
	estudiantes = Estudiante.objects.all()
	context = {'estudiantes':estudiantes}
	return render(request,"Estudiante_listar.html",context)

#def EstudianteList(request):
#	obj = Estudiante.objects.all()
#	for entrada in obj:
#		obj_nombre = entrada.nombre
#		obj_direccion = entrada.direccion
#		obj_carne = entrada.carne

#	context = {
#	"obj":   obj,
#	"obj_nombre":obj_nombre,
#	"obj_direccion":obj_direccion,
#	"obj_carne":obj_carne,

#	}
#	return render(request,"Estudiante_listar.html",context)


def BusList(request):
	obj = Bus.objects.all()
	context = {'obj':obj}
	return render(request,"EstudianteAdmin_listar.html",context)





# Create your views here.

class IndexView(TemplateView):
	template_name='index.html'

class EstudianteView(TemplateView):
	template_name='Estudiante.html'


class LoginView(FormView):
	template_name='login.html'
	form_class = AuthenticationForm
	success_url = reverse_lazy('App1:home')

	def form_valid(self, form):
		login(self.request, form.get_user())
		return super(LoginView, self).form_valid(form)


def logout_view(request):
	logout(request)
	return redirect('App1:home')








#class CrearEstudianteView(CreateView):
#template_name = 'crearEstudiante.html'
#form_class = EstudianteForm
#success_url = reverse_lazy('App1:home')

class crearEstudianteView(CreateView):
	template_name = 'crearEstudiante.html'
	form_class = EstudianteForm
	success_url = reverse_lazy('App1:home')


class crearBusView(CreateView):
	template_name = 'crearBus.html'
	form_class = BusForm
	success_url = reverse_lazy('App1:home')


	#Vistas para Editar
class EditarEstudianteView(UpdateView):
	template_name = 'crearEstudiante.html'
	model = Estudiante
	form_class = EstudianteForm
	success_url = reverse_lazy('App1:EstudianteList')

class EditarBusView(UpdateView):
	template_name = 'crearBus.html'
	model = Bus
	form_class = BusForm
	success_url = reverse_lazy('App1:home')



	#Vistaas para eliminar
class EliminarEstudianteView(DeleteView):
	template_name = 'Eliminar.html'
	model = Estudiante
	success_url = reverse_lazy('App1:EstudianteList')



class EliminarBusView(DeleteView):
	template_name = 'Eliminar.html'
	model = Bus
	success_url = reverse_lazy('App1:home')

Apps/usuario/views.py
from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.core.urlresolvers import reverse_lazy

from Apps.usuario.forms import RegistroForm
# Create your views here.


class RegistroUsuario (CreateView):
	model = User
	template_name = "registrar.html"
	form_class = RegistroForm
	success_url = reverse_lazy('App1:home')

Apps/Aplicacion1/templates/AcercaDe.html
{% extends 'base.html' %}

{% block contenido %}
<head>
	<title>Acerca De</title>
</head>
<body>
<h1>Desarrollo Web</h1> 
Practica del curso de desarrollo web Con Django <p>
De la carrera de ingenieria en Sistemas <p>
Docente: Ing. Ivan De Leon<p>
Estudiante: Wener Eladio González Miguel

</body>


{% endblock %}

Apps/Aplicacion1/templates/Administradores.html
{% extends 'crearEstudianteAdmin.html' %}

{% block tablaEstudianteAdmin %} 

<h1>Tabla Administradores</h1>
<h1 align="center">
<table border=4>
<tr>
	<td>Julian</td><td>Jarold</td><td>Ana</td>
</tr>
<tr>
	<td>Javier</td><td>Juaquin</td><td>Armando</td>
</tr>
</table>
{% endblock %}

Apps/Aplicacion1/templates/Articulo.html
{% extends 'base.html' %}

{% block contenido %}

	<h3 align="left">
		<form method="POST">
		 {% csrf_token %}

			Titulo <br>
			{{ form.titulo }}
			<br>
			Contenido del Articulo <br>
			{{ form.articulo }}
			<br>
			Fecha <br>
			 {{ form.fecha }}
			 <br>
			 Estudiante <br>
			{{ form.estudiante }}
			<br>
			 Estudiante Que Aprueba<br>
			{{ form.estudianteAdmin }}
			 <br><br>
			<button type="submit" value="Submit" class="btn btn-primary">Guardar</button>
	</h3>


<a href="{% url 'App1:ArticuloList' %}"> Listar Articulos</a>

{% block ListarArticulo %} {% endblock %}

</form>


{% endblock %}

Apps/Aplicacion1/templates/Articulo_List.html
{% extends 'Articulo.html' %}

{% block ListarArticulo %}

<h1>Lista de Articulos</h1>
<table class="table table-striped table-hover">
	<thead>
		<tr class="info success"> 
			<td>Titlulo</td>
			<td>Articulo</td>
			<td>Fecha</td>
			<td>Estudiante</td>
			<td>Estudiante Administrador</td>
			<td>Accion1</td>
			<td>Accion2</td>

		</tr>
	</thead>

	<tbody class="active">
			{% if articulos %}
			{% for articulo in articulos %}
			<tr>
				<td>{{ articulo.titulo }}</td>
				<td>{{ articulo.articulo }}</td>
				<td>{{ articulo.fecha }}</td>
				<td>{{ articulo.estudiante }}</td>
				<td>{{ articulo.estudianteAdmin }}</td>
				<td><a href="{% url 'App1:EditarArticulo' articulo.id %}">Editar</a></td>
				<td><a href="{% url 'App1:DeleteArticulo' articulo.id %}">Eliminar</a></td>
			</tr>
			{% endfor %}
			{% else %}
			<h2>No hay registros </h2>
			{% endif %}
	</tbody>
</table>
<a href ="{% url 'App1:Articulo' %}" class="btn btn-primary"> Agregar Articulo </a>

{% endblock %}

Apps/Aplicacion1/templates/Comentario.html
{% extends 'base.html' %}

{% block contenido %}

<h3 align="left" style="color:">
<form method="POST">
 {% csrf_token %}
Contenido Comentario<br>
{{ form.comentario }}
<br>
Fecha <br>
{{ form.fecha }}
<br>
 Estudiante <br>
{{ form.estudiante }}
<br>
Articulo <br>
{{ form.articulo }}
 <br><br>
<button type="submit" value="Submit" class="btn btn-primary">Guardar</button>

</h3>
</form>


{% endblock %}

Apps/Aplicacion1/templates/Eliminar.html
{% extends 'base.html' %}

{% block contenido %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea Eliminar el registro {{ object.nombre }} {{ object.titulo}}?</h3>
	<button class="btn btn-danger" type="submit"> Sí, Eliminar</button>
	<A  class="btn btn-default" HREF="{% url 'App1:EstudianteList' %}" onclick="clicked()">Cancelar</A>
<h3>
</h3>
</form>

{% endblock %}

Apps/Aplicacion1/templates/EstudianteAdmin_listar.html
{% extends 'crearEstudianteAdmin.html' %}

{% block tablaAdmin %}

	<html>
		<h1>Tabla Estudiantes Administradores</h1>

	<div>
	
	<table class="table table-striped table-hover">
		<tr class="info">
			<td>Nombre<td>Carne<td>Direccion<td>Accion1<td>Accion2</td>
		</tr class="success">


		{% for est in obj %}

		<tr class="active">
			<td>{{est.nombre}}
			<td>{{est.direccion}}
			<td>{{est.carne}}
			<td><a href="{% url 'App1:EditarEstudianteAdmin' est.id %}" >Editar</a>
			<td><a href="{% url 'App1:DeleteAdmin' est.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
	</table>

</div>

<A HREF="{% url 'App1:AddEstudianteAdmin' %}" class="btn btn-default">Agregar un Nuevo estudiante</A>

</html>
{% endblock %}

Apps/Aplicacion1/templates/Estudiante_listar.html
{% extends 'crearEstudiante.html' %}

{% block tablaEstudiante %}
<html>

</h2>

<div>
	<table class="table table-striped table-hover">
		<tr class="info success">
			<td>Nombre</td>
			<td>Carne</td>
			<td>Direccion</td>
			<td>Accion</td>
			<td>Accion 2</td>
		</tr>

		{% if estudiantes %}
				{% for est in estudiantes %}

		<tr class="active">
			<td>{{est.nombre}}</td>
			<td>{{est.direccion}}</td>
			<td>{{est.carne}}</td>
	
			<td><a href="{% url 'App1:EditarEstudiante' est.id %}">Editar</a></td>
			<td><a href="{% url 'App1:DeleteEstudiante' est.id %}">Eliminar</a>
			</td>
			
		</tr>
				{% endfor %}
		{% else %}
		<h2>No hay Registros</h2>
		{% endif %}

	</table>

</div>


<A HREF="{% url 'App1:addEstudiante' %}" class="btn btn-default">Agregar un Nuevo estudiante</A>


</table>
</h2>

</html>
{% endblock %}

Apps/Aplicacion1/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Business Casual - Start Bootstrap Theme</title>

    <!-- Bootstrap core CSS -->
    {% load static %}

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/business-casual.css' %}" rel="stylesheet">

  </head>

  <body>


    <div class="tagline-upper text-center text-heading text-shadow text-white mt-5 d-none d-lg-block">Desarrollo Web</div>
    <div class="tagline-lower text-center text-expanded text-shadow text-uppercase text-white mb-5 d-none d-lg-block">3481 Melrose Place | Beverly Hills, CA 90210 | 123.456.7890</div>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-faded py-lg-4">
      <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item active px-lg-4">
                <a href="{% url 'App1:home' %}" class="nav-link text-uppercase text-expanded">Principal</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'App1:addEstudiante' %}">Estudiante</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{%url 'App1:addBus' %}" >Administrador</a>
            </li>
            
            {% if user.is_authenticated %}
          <a href="{% url 'App1:logout'%}" class="btn btn-primary">Logout</a>
          <h3>Usuario: {{ user.username }} 
          </h3>
{% else %}
    <a href="{% url 'App1:login'%}" class="btn btn-primary">Login</a>
    <a href="{% url 'usuario:Registro' %}" class="btn btn-success">Registrar</a>
{% endif %}
</a>
          </ul>
        </div>
      </div>
    </nav>


<div class="container">

      <div class="bg-faded p-4 my-4">
        <!-- Image Carousel -->
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        
        

      <div class="bg-faded p-4 my-4">
        <hr class="divider">
        <h2 class="text-center text-lg text-uppercase my-0">Build a website
          <strong>worth visitng</strong>
        </h2>
        <hr class="divider">
        {% block contenido %} {% endblock %}
       

    
      </div>

    </div>










 



    <div class="container">

      <div class="bg-faded p-4 my-4">
        <!-- Image Carousel -->
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid w-100" src="{% static 'img/slide-1.jpg' %}" alt="">
              <div class="carousel-caption d-none d-md-block">
                <h3 class="text-shadow">First Slide</h3>
                <p class="text-shadow">This is the caption for the first slide.</p>
              </div>
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid w-100" src="{% static 'img/slide-2.jpg' %}" alt="">
              <div class="carousel-caption d-none d-md-block">
                <h3 class="text-shadow">Second Slide</h3>
                <p class="text-shadow">This is the caption for the second slide.</p>
              </div>
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid w-100" src="{% static 'img/slide-3.jpg' %}" alt="">
              <div class="carousel-caption d-none d-md-block">
                <h3 class="text-shadow">Third Slide</h3>
                <p class="text-shadow">This is the caption for the third slide.</p>
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        <!-- Welcome Message -->
        <div class="text-center mt-4">
          <div class="text-heading text-muted text-lg">Welcome To</div>
          <h1 class="my-2">Business Casual</h1>
          <div class="text-heading text-muted text-lg">By
            <strong>Start Bootstrap</strong>
          </div>
        </div>
      </div>

      

    </div>
    <!-- /.container -->

    <footer class="bg-faded text-center py-5">
      <div class="container">
        <p class="m-0">Copyright &copy; Your Website 2017</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

  </body>

</html>

Apps/Aplicacion1/templates/crearEstudiante.html
{% extends 'base.html' %}

{% block contenido %}

<body>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Registrar Estudiante</h3>
  </div>
  <div class="panel-body" >
   <form method="POST">
 <h3 align="left" style="color:">
 		{% csrf_token %}

		Nombre <br>
		{{ form.nombre }}
		<br>
		Direccion <br>
		{{ form.direccion }}
		<br>
		Carné <br>
		 {{ form.carne }}
		 <br><br>
		<button type="submit" value="Submit" class="btn btn-primary">Agregar</button>


</h3>


</form>

</body>
<A HREF="{% url 'App1:EstudianteList' %}" onclick="clicked()">Ver Estudiantes</A>
<h3>
{% block tablaEstudiante %} {% endblock %}
</h3>



{% endblock %}

Apps/Aplicacion1/templates/crearEstudianteAdmin.html
{% extends 'base.html' %}

{% block contenido %}

<h2>Estudiante Administrador</h2>

<h3 align="left">
<form method="POST">
 {% csrf_token %}
Nombre <br>
{{ form.nombre }}
<br>
Direccion <br>
{{ form.direccion }}
<br>
Carné <br>
 {{ form.carne }}
 <br><br>
<button type="submit" class="btn btn-primary" value="Submit">Agregar</button>

</h3>
</form>

<A HREF="{% url 'App1:EstudianteListAdmin' %}">Ver Estudiantes administradores</A>

<h3>
{% block tablaAdmin %} {% endblock %}
</h3>

{% endblock %}

Apps/Aplicacion1/templates/index.html
{% extends 'base.html' %}

{% block contenido %}

<body>
	<h2>Orígenes y Filosofía</h2>
<p>La Universidad Mariano Gálvez , es una institución de educación superior,	 privada, independiente, no lucrativa, que funciona de acuerdo con las leyes propias de su naturaleza institucional, que fue aprobada el 29 de Enero de 1966, por el Consejo Supremo Universitario de la Universidad de San Carlos de Guatemala.
</p>
<p>
Su nombre hace honor al eximio estadista, prócer y preclaro jurisconsulto Doctor José Mariano Gálvez (Jefe del Estado de Guatemala 1831-1838), fundador de la Academia de Estudios y reformador de la educación guatemalteca, quien promovió importantes innovaciones en todos los órdenes de la vida del Estado. Se le atribuye el mejoramiento de la instrucción pública. Luchó por que la enseñanza fuera laica, fue fundador de la Biblioteca y Museo Nacional, respetó las leyes y garantías individuales, libertad de prensa y emisión del pensamiento.
</p>
</body>

{% endblock %}

Apps/Aplicacion1/templates/login.html
{% extends 'base.html' %}

{% block contenido %}

<h3 align="center"">
<form method="POST">
 {% csrf_token %}

User <br>
{{ form.username }}
<br>
Password <br>
{{ form.password }}
 <br><br>

<button type="submit" value="Submit" class="btn btn-primary" >Ingresar</button>

</h3>
</form>


{% endblock %}

Apps/usuario/templates/registrar.html
{% extends 'base.html' %}

{%block contenido %}
<form method="POST">
 {% csrf_token %}
 <h4>
 <br>
 Nombre de usuario <br>
	{{form.username}}
 <br>
 Nombre <br>
	{{form.first_name}}
 <br>
 Correo <br>
	{{form.email}}
 <br>
  Contraseña <br>
	{{form.password1}}
 <br>
  Confirmar Contraseña <br>
	{{form.password2}}
 <br>
La contraseña debe contener letras y numeros
</h4>
<button type="submit" class="btn btn-primary">Guardar</button>

{% endblock %}